### ISSUE TITLE
Make KinshipContext without Type Definitions friendly against Linting Errors / TypeScript compiling errors

### ISSUE THREAD

**Issue by traviszuleger** [kinshipjs/core#11]
**Is your feature request related to a problem? Please describe.**
Currently, if a KinshipContext is defined with no type definitions, then many clause functions will show linting or typescript errors, mostly to do with the Proxies that are set up expecting a type definition.

**Describe the solution you'd like**
If a KinshipContext is defined with no type definitions, then all clause functions' proxies should inherently know that there whatever the User is going to give can be deemed as trustworthy, and no linting or typescript errors should show.

```ts
const ctx = new KinshipContext<{ id: number, foo: string }>(cnn, "Table");

// since the context has been defined with the type `{ id: number, foo: string }`, then no linting errors will throw 
ctx.where(m => m.foo.equals("test"));
```

However,

```js
const ctx = new KinshipContext(cnn, "Table");

// since the context has no type definition, then linting/typescript errors will show on `m.foo`
ctx.where(m => m.foo.equals("test"));
```

It is expected that if a User is to use a `KinshipContext` with no type definition, then all that they are giving up should be is the type safety. They should still be able to use the context normally with no clutter of linting errors or problems with typescript compilers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tzuleger** [comment]
A solution will be available in 0.2.0
